---
- hosts: personal
  roles:
    - role: bluk.homebrew
      vars:
        homebrew_taps:
          - name: homebrew/bundle
          - name: homebrew/core
          - name: vapor/tap
        homebrew_packages:
          - name: ack
          - name: bash
          - name: bash-completion
          - name: ctags
          - name: curl
          - name: git
          - name: go
          - name: gnupg
          - name: kubernetes-cli
          - name: kubernetes-helm
          - name: libtool
          - name: pinentry-mac
          - name: protobuf
          - name: reattach-to-user-namespace
          - name: swiftlint
          - name: tmux
          - name: vapor/tap/vapor
          - name: vim
          - name: wget
          - name: yubico-piv-tool
        homebrew_casks:
          - name: minikube
        homebrew_update: true
        homebrew_upgrade: true
    - role: bluk.nodenv
    - role: bluk.rbenv
    - role: bluk.pyenv
    - role: bluk.grpc_swift
      vars:
        grpc_swift_install_path: ~/provision/grpc-swift
        grpc_swift_git_url: https://github.com/grpc/grpc-swift.git
        grpc_swift_git_update: true
        grpc_swift_binary_install_path: /usr/local/bin/
    - role: bluk.git_clone
      vars:
        git_repos:
          - url: git@github.com:junegunn/fzf.git
            dest: "~/.fzf"
    - role: bluk.symlink_repo
      vars:
        git_repo: "git@github.com:bluk/dotfiles.git"
        git_repo_local_dest: "~/provision/dotfiles"
        git_repo_dir_src: "home"
        symlink_local_dest: "~"
        symlink_local_force_replace: yes
    - role: bluk.symlink_repo
      vars:
        git_repo: "git@github.com:bluk/dotfiles.git"
        git_repo_local_dest: "~/provision/dotfiles"
        git_repo_dir_src: "gnupg"
        symlink_local_dest: "~/.gnupg"
        symlink_local_force_replace: yes
    - role: bluk.symlink_repo
      vars:
        git_repo: "git@github.com:bluk/configs.git"
        git_repo_local_dest: "~/Code/configs"
        git_repo_dir_src: "home"
        symlink_local_dest: "~"
        symlink_local_force_replace: no

    # Must be after the config is pulled down

    - role: bluk.import_gpg_repo
      vars:
        git_repo: "git@github.com:bluk/public-gpg-keys.git"
        git_repo_local_dest: "~/provision/public-gpg-keys"
        git_repo_dir_src: "keys"
    - role: vim
