---
- hosts: personal
  roles:
    - role: bluk.homebrew
      vars:
        homebrew_taps:
          - name: homebrew/bundle
          - name: homebrew/core
          - name: vapor/tap
        homebrew_packages:
          - name: ack
          - name: asciinema
          - name: bash
          - name: bash-completion
          - name: ctags
          - name: curl
          - name: direnv
          - name: fish
          - name: git
          - name: gnupg
          - name: hub
          - name: hugo
          - name: jq
          - name: kubernetes-cli
          - name: kubernetes-helm
          - name: libtool
          - name: libxml2
          - name: neovim
          - name: nghttp2
          - name: pinentry-mac
          - name: protobuf
          - name: reattach-to-user-namespace
          - name: sqlite3
          - name: swiftformat
          - name: swiftlint
          - name: tmux
          - name: vim
          - name: wget
          - name: yubico-piv-tool
          - name: zlib
        # homebrew_casks:
        #   - name: minikube
        #   - name: fastlane
        homebrew_update: true
        homebrew_upgrade: true
    - role: bluk.nodenv
    - role: bluk.rbenv
    - role: bluk.pyenv
    - role: bluk.goenv
    - role: bluk.git_clone
      vars:
        git_repos:
          - url: git@github.com:junegunn/fzf.git
            dest: "~/.fzf"
          - url: https://github.com/tmux-plugins/tpm
            dest: "~/.tmux/plugins/tpm"
          - url: git@github.com:apple/sourcekit-lsp.git
            dest: "~/provision/sourcekit-lsp"
    - role: bluk.symlink_repo
      vars:
        git_repo: "git@github.com:bluk/dotfiles.git"
        git_repo_local_dest: "~/provision/dotfiles"
        git_repo_dir_src: "home"
        symlink_local_dest: "~"
        symlink_local_force_replace: yes
    - role: bluk.symlink_repo
      vars:
        git_repo: "git@github.com:bluk/dotfiles.git"
        git_repo_local_dest: "~/provision/dotfiles"
        git_repo_dir_src: "gnupg"
        symlink_local_dest: "~/.gnupg"
        symlink_local_force_replace: yes
    - role: bluk.symlink_repo
      vars:
        git_repo: "git@github.com:bluk/dotfiles.git"
        git_repo_local_dest: "~/provision/dotfiles"
        git_repo_dir_src: "config"
        symlink_local_dest: "~/.config/"
        symlink_local_force_replace: yes
    - role: bluk.symlink_repo
      vars:
        git_repo: "git@github.com:bluk/dotfiles.git"
        git_repo_local_dest: "~/provision/dotfiles"
        git_repo_dir_src: "local/share/nvim/site/autoload"
        symlink_local_dest: "~/.local/share/nvim/site/autoload/"
        symlink_local_force_replace: yes
    - role: bluk.symlink_repo
      vars:
        git_repo: "git@github.com:bluk/dotfiles.git"
        git_repo_local_dest: "~/provision/dotfiles"
        git_repo_dir_src: "bash_completion"
        symlink_local_dest: "/usr/local/etc/bash_completion.d/"
        symlink_local_force_replace: yes

    # Must be after the dotfiles is pulled down

    - role: bluk.import_gpg_repo
      vars:
        git_repo: "git@github.com:bluk/public-gpg-keys.git"
        git_repo_local_dest: "~/provision/public-gpg-keys"
        git_repo_dir_src: "keys"
    - role: bluk.hashicorp
      vars:
        hashicorp_program: vault
        hashicorp_version: 1.6.1
        hashicorp_platform: darwin_amd64
        hashicorp_install_path: /usr/local/bin
    - role: bluk.hashicorp
      vars:
        hashicorp_program: consul
        hashicorp_version: 1.9.1
        hashicorp_platform: darwin_amd64
        hashicorp_install_path: /usr/local/bin
    - role: bluk.hashicorp
      vars:
        hashicorp_program: terraform
        hashicorp_version: 0.14.4
        hashicorp_platform: darwin_amd64
        hashicorp_install_path: /usr/local/bin
    - role: bluk.hashicorp
      vars:
        hashicorp_program: nomad
        hashicorp_version: 1.0.1
        hashicorp_platform: darwin_amd64
        hashicorp_install_path: /usr/local/bin
    - role: bluk.hashicorp
      vars:
        hashicorp_program: packer
        hashicorp_version: 1.6.6
        hashicorp_platform: darwin_amd64
        hashicorp_install_path: /usr/local/bin
    - role: bluk.hashicorp
      vars:
        hashicorp_program: consul-template
        hashicorp_version: 0.19.5
        hashicorp_platform: darwin_amd64
        hashicorp_install_path: /usr/local/bin
    - role: bluk.hashicorp
      vars:
        hashicorp_program: envconsul
        hashicorp_version: 0.7.3
        hashicorp_platform: darwin_amd64
        hashicorp_install_path: /usr/local/bin
    # - role: bluk.op_cli
    #   vars:
    #     op_cli_version: 0.8.0
    #     op_cli_platform: darwin_amd64
    #     op_cli_install_path: /usr/local/bin
  tasks:
    - name: Install Universal ctags
      shell: brew install --HEAD universal-ctags/universal-ctags/universal-ctags
    # - name: Install Ruby
    #   shell: export LDFLAGS="-L/usr/local/opt/zlib/lib -L/usr/local/opt/sqlite/lib" && export CPPFLAGS="-I/usr/local/opt/zlib/include -I/usr/local/opt/sqlite/include" && rbenv install -s 2.7.1
    # - name: Use Ruby
    #   shell: rbenv global 2.7.1
    # - name: Install Python 3
    #   shell: export LDFLAGS="-L/usr/local/opt/zlib/lib -L/usr/local/opt/sqlite/lib" && export CPPFLAGS="-I/usr/local/opt/zlib/include -I/usr/local/opt/sqlite/include" && pyenv install -s 3.8.3
    # - name: Install Python 2
    #   shell: export LDFLAGS="-L/usr/local/opt/zlib/lib -L/usr/local/opt/sqlite/lib" && export CPPFLAGS="-I/usr/local/opt/zlib/include -I/usr/local/opt/sqlite/include" && pyenv install -s 2.7.17
    # - name: Use Python 3
    #   shell: pyenv global 3.8.3 2.7.17
    - name: Install Node
      shell: export LDFLAGS="-L/usr/local/opt/zlib/lib -L/usr/local/opt/sqlite/lib" && export CPPFLAGS="-I/usr/local/opt/zlib/include -I/usr/local/opt/sqlite/include" && nodenv install -s 15.0.0
    - name: Use Node
      shell: nodenv global 15.0.0
    # - name: Install Go
    #   shell: goenv install -s 1.15.2
    # - name: Use Go
    #   shell: goenv global 1.15.2
    - name: Install Rust
      shell: curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path --default-toolchain stable -y
    - name: Install Rust Toolchain Stable
      shell: rustup update
    - name: Install Rust Toolchain Stable
      shell: rustup toolchain install stable
    - name: Install Rust Components
      shell: rustup component add rls rust-analysis rust-src rustfmt clippy
    - name: Install bash-language-server
      command: "npm i -g bash-language-server"
    - name: Install vscode-json-languageserver
      command: "npm i -g vscode-json-languageserver"
    - name: Install vscode-html-languageserver-bin
      command: "npm i -g vscode-html-languageserver-bin"
    - name: Install vscode-css-languageserver-bin
      command: "npm i -g vscode-css-languageserver-bin"
    - name: Install yaml-language-server
      command: "npm i -g yaml-language-server"
    # - name: Install go-langserver
    #   shell: "go get -u github.com/sourcegraph/go-langserver"
    - name: Install javascript-typescript-langserver
      command: "npm i -g javascript-typescript-langserver"
    - name: Install typescript-language-server
      command: "npm install -g typescript typescript-language-server"
    # - name: Install python-language-server
    #   command: "pip install 'python-language-server[all]'"
    - name: Install fzf bin
      shell: ~/.fzf/install --bin
    - name: Install vim plugins
      shell: vim +PlugClean! +PlugInstall +qall
    - name: Install nvim plugins
      shell: nvim +PlugClean! +PlugInstall +qall
