---
- hosts: personal
  roles:
    - role: bluk.homebrew
      vars:
        homebrew_taps:
          - name: homebrew/bundle
          - name: homebrew/core
          - name: vapor/tap
        homebrew_packages:
          - name: ack
          - name: asciinema
          - name: bash
          - name: bash-completion
          - name: ctags
          - name: curl
          - name: direnv
          - name: fpp
          - name: git
          - name: gnupg
          - name: hub
          - name: jq
          - name: kubernetes-cli
          - name: kubernetes-helm
          - name: libtool
          - name: libxml2
          - name: pinentry-mac
          - name: protobuf
          - name: reattach-to-user-namespace
          - name: swiftformat
          - name: swiftlint
          - name: tmux
          - name: vapor/tap/vapor
          - name: vim
          - name: wget
          - name: yubico-piv-tool
          - name: zlib
        homebrew_casks:
          - name: minikube
        homebrew_update: true
        homebrew_upgrade: true
    - role: bluk.nodenv
    - role: bluk.rbenv
    - role: bluk.pyenv
    - role: bluk.goenv
    - role: bluk.grpc_swift
      vars:
        grpc_swift_install_path: ~/provision/grpc-swift
        grpc_swift_git_url: https://github.com/grpc/grpc-swift.git
        grpc_swift_git_update: true
        grpc_swift_binary_install_path: /usr/local/bin/
    - role: bluk.git_clone
      vars:
        git_repos:
          - url: git@github.com:junegunn/fzf.git
            dest: "~/.fzf"
    - role: bluk.symlink_repo
      vars:
        git_repo: "git@github.com:bluk/dotfiles.git"
        git_repo_local_dest: "~/provision/dotfiles"
        git_repo_dir_src: "home"
        symlink_local_dest: "~"
        symlink_local_force_replace: yes
    - role: bluk.symlink_repo
      vars:
        git_repo: "git@github.com:bluk/dotfiles.git"
        git_repo_local_dest: "~/provision/dotfiles"
        git_repo_dir_src: "gnupg"
        symlink_local_dest: "~/.gnupg"
        symlink_local_force_replace: yes
    - role: bluk.symlink_repo
      vars:
        git_repo: "git@github.com:bluk/dotfiles.git"
        git_repo_local_dest: "~/provision/dotfiles"
        git_repo_dir_src: "bash_completion"
        symlink_local_dest: "/usr/local/etc/bash_completion.d/"
        symlink_local_force_replace: yes

    # Must be after the dotfiles is pulled down

    - role: bluk.import_gpg_repo
      vars:
        git_repo: "git@github.com:bluk/public-gpg-keys.git"
        git_repo_local_dest: "~/provision/public-gpg-keys"
        git_repo_dir_src: "keys"
    - role: bluk.hashicorp
      vars:
        hashicorp_program: vault
        hashicorp_version: 0.11.3
        hashicorp_platform: darwin_amd64
        hashicorp_install_path: /usr/local/bin
    - role: bluk.hashicorp
      vars:
        hashicorp_program: consul
        hashicorp_version: 1.3.0
        hashicorp_platform: darwin_amd64
        hashicorp_install_path: /usr/local/bin
    - role: bluk.hashicorp
      vars:
        hashicorp_program: terraform
        hashicorp_version: 0.11.8
        hashicorp_platform: darwin_amd64
        hashicorp_install_path: /usr/local/bin
    - role: bluk.hashicorp
      vars:
        hashicorp_program: nomad
        hashicorp_version: 0.8.6
        hashicorp_platform: darwin_amd64
        hashicorp_install_path: /usr/local/bin
    - role: bluk.hashicorp
      vars:
        hashicorp_program: packer
        hashicorp_version: 1.3.1
        hashicorp_platform: darwin_amd64
        hashicorp_install_path: /usr/local/bin
    - role: bluk.hashicorp
      vars:
        hashicorp_program: consul-template
        hashicorp_version: 0.19.5
        hashicorp_platform: darwin_amd64
        hashicorp_install_path: /usr/local/bin
    - role: bluk.hashicorp
      vars:
        hashicorp_program: envconsul
        hashicorp_version: 0.7.3
        hashicorp_platform: darwin_amd64
        hashicorp_install_path: /usr/local/bin
    - role: bluk.op_cli
      vars:
        op_cli_version: 0.5.4
        op_cli_platform: darwin_amd64
        op_cli_install_path: /usr/local/bin
  tasks:
    - name: Install Ruby
      shell: export LDFLAGS="-L/usr/local/opt/zlib/lib" && export CPPFLAGS="-I/usr/local/opt/zlib/include" && rbenv install -s 2.5.3
    - name: Use Ruby
      shell: rbenv global 2.5.3
    - name: Install Python 3
      shell: export LDFLAGS="-L/usr/local/opt/zlib/lib" && export CPPFLAGS="-I/usr/local/opt/zlib/include" && pyenv install -s 3.7.0
    - name: Install Python 2.7.15
      shell: export LDFLAGS="-L/usr/local/opt/zlib/lib" && export CPPFLAGS="-I/usr/local/opt/zlib/include" && pyenv install -s 2.7.15
    - name: Use Python 3
      shell: pyenv global 3.7.0 2.7.15
    - name: Install Node
      shell: export LDFLAGS="-L/usr/local/opt/zlib/lib" && export CPPFLAGS="-I/usr/local/opt/zlib/include" && nodenv install -s 10.12.0
    - name: Use Node
      shell: nodenv global 10.12.0
    - name: Install Go
      shell: goenv install -s 1.11.1
    - name: Use Go
      shell: goenv global 1.11.1
    - name: Install neovim for vim plugin
      shell: "pip3 install neovim"
    - name: Install dockerfile-language-server-nodejs
      command: "npm install -g dockerfile-language-server-nodejs"
    - name: Install dockerfile-language-server-nodejs
      command: "npm i -g bash-language-server"
    - name: Install vscode-json-languageserver
      command: "npm i -g vscode-json-languageserver"
    - name: Install vscode-html-languageserver-bin
      command: "npm i -g vscode-html-languageserver-bin"
    - name: Install vscode-css-languageserver-bin
      command: "npm i -g vscode-css-languageserver-bin"
    - name: Install yaml-language-server
      command: "npm i -g yaml-language-server"
    - name: Install go-langserver
      command: "go get -u github.com/sourcegraph/go-langserver"
    - name: Install javascript-typescript-langserver
      command: "npm i -g javascript-typescript-langserver"
    - name: Install python-language-server
      command: "pip install 'python-language-server[all]'"
    - name: Install fzf bin
      shell: ~/.fzf/install --bin
    - name: Install vim plugins
      shell: vim +PlugInstall +PlugClean! +qall
