---
- hosts: personal
  roles:
    - role: bluk.homebrew
      vars:
        homebrew_taps:
          - name: homebrew/bundle
          - name: homebrew/core
          - name: vapor/tap
        homebrew_packages:
          - name: ack
          - name: bash
          - name: bash-completion
          - name: ctags
          - name: curl
          - name: fpp
          - name: git
          - name: go
          - name: gnupg
          - name: jq
          - name: kubernetes-cli
          - name: kubernetes-helm
          - name: libtool
          - name: libxml2
          - name: pinentry-mac
          - name: protobuf
          - name: reattach-to-user-namespace
          - name: swiftlint
          - name: tmux
          - name: vapor/tap/vapor
          - name: vim
          - name: wget
          - name: yubico-piv-tool
        homebrew_casks:
          - name: minikube
        homebrew_update: true
        homebrew_upgrade: true
    - role: bluk.nodenv
    - role: bluk.rbenv
    - role: bluk.pyenv
    - role: bluk.grpc_swift
      vars:
        grpc_swift_install_path: ~/provision/grpc-swift
        grpc_swift_git_url: https://github.com/grpc/grpc-swift.git
        grpc_swift_git_update: true
        grpc_swift_binary_install_path: /usr/local/bin/
    - role: bluk.git_clone
      vars:
        git_repos:
          - url: git@github.com:junegunn/fzf.git
            dest: "~/.fzf"
    - role: bluk.symlink_repo
      vars:
        git_repo: "git@github.com:bluk/dotfiles.git"
        git_repo_local_dest: "~/provision/dotfiles"
        git_repo_dir_src: "home"
        symlink_local_dest: "~"
        symlink_local_force_replace: yes
    - role: bluk.symlink_repo
      vars:
        git_repo: "git@github.com:bluk/dotfiles.git"
        git_repo_local_dest: "~/provision/dotfiles"
        git_repo_dir_src: "gnupg"
        symlink_local_dest: "~/.gnupg"
        symlink_local_force_replace: yes
    - role: bluk.symlink_repo
      vars:
        git_repo: "git@github.com:bluk/dotfiles.git"
        git_repo_local_dest: "~/provision/dotfiles"
        git_repo_dir_src: "bash_completion"
        symlink_local_dest: "/usr/local/etc/bash_completion.d/"
        symlink_local_force_replace: yes

    # Must be after the dotfiles is pulled down

    - role: bluk.import_gpg_repo
      vars:
        git_repo: "git@github.com:bluk/public-gpg-keys.git"
        git_repo_local_dest: "~/provision/public-gpg-keys"
        git_repo_dir_src: "keys"
    - role: vim
    - role: bluk.hashicorp
      vars:
        hashicorp_program: vault
        hashicorp_version: 0.11.1
        hashicorp_platform: darwin_amd64
        hashicorp_install_path: /usr/local/bin
    - role: bluk.hashicorp
      vars:
        hashicorp_program: consul
        hashicorp_version: 1.2.3
        hashicorp_platform: darwin_amd64
        hashicorp_install_path: /usr/local/bin
    - role: bluk.hashicorp
      vars:
        hashicorp_program: terraform
        hashicorp_version: 0.11.8
        hashicorp_platform: darwin_amd64
        hashicorp_install_path: /usr/local/bin
    - role: bluk.hashicorp
      vars:
        hashicorp_program: nomad
        hashicorp_version: 0.8.5
        hashicorp_platform: darwin_amd64
        hashicorp_install_path: /usr/local/bin
    - role: bluk.hashicorp
      vars:
        hashicorp_program: packer
        hashicorp_version: 1.3.1
        hashicorp_platform: darwin_amd64
        hashicorp_install_path: /usr/local/bin
    - role: bluk.hashicorp
      vars:
        hashicorp_program: consul-template
        hashicorp_version: 0.19.5
        hashicorp_platform: darwin_amd64
        hashicorp_install_path: /usr/local/bin
    - role: bluk.hashicorp
      vars:
        hashicorp_program: envconsul
        hashicorp_version: 0.7.3
        hashicorp_platform: darwin_amd64
        hashicorp_install_path: /usr/local/bin
    - role: bluk.op_cli
      vars:
        op_cli_version: 0.5.3
        op_cli_platform: darwin_amd64
        op_cli_install_path: /usr/local/bin
