- src: https://github.com/bluk/ansible-role-nodenv.git
  name: bluk.nodenv
  version: v0.1.1
- src: https://github.com/bluk/ansible-role-rbenv.git
  name: bluk.rbenv
  version: v0.1.0
- src: https://github.com/bluk/ansible-role-pyenv.git
  name: bluk.pyenv
  version: v0.1.0
- src: https://github.com/bluk/ansible-role-goenv.git
  name: bluk.goenv
  version: v0.1.0
- src: https://github.com/bluk/ansible-role-swiftenv.git
  name: bluk.swiftenv
  version: v0.1.1
- src: https://github.com/bluk/ansible-role-symlink-repo.git
  name: bluk.symlink_repo
  version: v0.4.0
- src: https://github.com/bluk/ansible-role-import-gpg-repo.git
  name: bluk.import_gpg_repo
  version: v0.2.0
- src: https://github.com/bluk/ansible-role-homebrew.git
  name: bluk.homebrew
  version: v0.2.0
- src: https://github.com/bluk/ansible-role-git-clone.git
  name: bluk.git_clone
  version: v0.2.0
- src: https://github.com/bluk/ansible-role-grpc-swift.git
  name: bluk.grpc_swift
  version: v0.1.0
- src: https://github.com/bluk/ansible-role-hashicorp.git
  name: bluk.hashicorp
  version: v0.2.0
- src: https://github.com/bluk/ansible-role-1password-cli.git
  name: bluk.op_cli
  version: v0.2.0
