- src: https://github.com/bluk/ansible-role-nodenv.git
  name: bluk.nodenv
  version: master
- src: https://github.com/bluk/ansible-role-rbenv.git
  name: bluk.rbenv
  version: master
- src: https://github.com/bluk/ansible-role-symlink-repo.git
  name: bluk.symlink_repo
  version: master
- src: https://github.com/bluk/ansible-role-import-gpg-repo.git
  name: bluk.import_gpg_repo
  version: master
- src: https://github.com/bluk/ansible-role-homebrew.git
  name: bluk.homebrew
  version: master
- src: https://github.com/bluk/ansible-role-git-clone.git
  name: bluk.git_clone
  version: master
- src: https://github.com/bluk/ansible-role-grpc-swift.git
  name: bluk.grpc_swift
  version: master
