---

- name: Create vim backup directory
  file:
    path: ~/.vim/backup
    state: directory
    mode: 0755
- name: Create vim swap directory
  file:
    path: ~/.vim/swap
    state: directory
    mode: 0755
- name: Create vim undo directory
  file:
    path: ~/.vim/undo
    state: directory
    mode: 0755
- name: Install vim plugins
  shell: vim +PlugInstall +PlugClean! +qall
